### ISSUE TITLE
專案聊天室

### ISSUE THREAD

**Issue by ascendbruce** [taiwanese-work-in/foreign-country#13]
## Why is this change necessary
- 方便非正式交流
## Proposed solution
- 開 LINE 或 Facebook Group chat
- 甚至每個國家一個頻道
- Slack 要註冊挺麻煩，個人不太推
## Definition of done
- 開啟聊天室
- 連結放在 README 或 wiki 裡

**Comment by yorkxin** [comment]
LINE 或 Facebook Group 我都不喜歡，因為會一直 notify 很煩。

我倒是比較喜歡 Slack，一個國家一個 channel，也可以有共同頻道例如 “taiwan”。

話說 Slack 註冊很麻煩是怎麼樣的情況？

**Comment by ascendbruce** [comment]
就是... 要去 xxx.slack.com 註冊一個帳號，還要想個密碼 (沒有用 1password 之前)，個人覺得有點麻煩 XD...

另外 slack 還有不給錢不給看歷史記錄的問題，雖然看不到就算了... (?)

**Comment by ascendbruce** [comment]
另外還有一個情況要考慮是：可能會有非技術類工作的人加入。所以 gitter 不在我的考慮範圍了 (之前開的 gitter 頻道蠻冷清的...)

**Comment by yorkxin** [comment]
我發現我搞錯了，你說的 Facebook Group 應該是 Facebook 社團？如果是社團的話我覺得不錯，門檻很低，而且我們可以跟現有的社團合作就好，例如「台灣開發者在澳洲」。

**Comment by ascendbruce** [comment]
其實你沒有想錯，我是想開 Facebook Group 然後對整個 group 開一個 messager conversation XD

**Comment by tslcjames** [comment]
@ascendbruce 不知道在哪邊發問, 所以問在這邊
請問有計劃開發其他國家嗎？  我在雅加達工作....有點奇妙就是ＸＤ

**Comment by ascendbruce** [comment]
@tslcjames 「有人」願意當主編的話，我們很樂意開發新國家唷！意下如何？ XD

**Comment by tslcjames** [comment]
好啊！我們該如何進行?

**Comment by ascendbruce** [comment]
Hi @tslcjames, 太好了！

我已經開好印尼 project：https://github.com/taiwanese-work-in/indonesia

也邀請您加入 GitHub 群組了（請檢查 email）

可以先參考其他國家的 wiki 文章分類法，但沒有什麼統一格式

各國工作都適用的文章（例如如何處理台灣的健保等），可以集中到這個 wiki： https://github.com/taiwanese-work-in/foreign-country/wiki

有任何問題可以直接丟我 FB/Twitter/Gmail `ascendbruce` (應該說、有空的時候丟個訊息給我唄，可以再跟你討論一些細節 XD)

**Comment by ascendbruce** [comment]
現階段已無需求
