### ISSUE TITLE
更換網站 favicon

### ISSUE THREAD

**Issue by ascendbruce** [taiwanese-work-in/foreign-country#14]
## Why is this change necessary
- 更有整體性
## Proposed solution
- 尋找免費 icon 或畫一個簡單的圖示來取代目前的網站 favicon
## Definition of done
- 更換 favicon 並 deploy production

---
## Things to do

Ref: https://github.com/audreyr/favicon-cheat-sheet
- [x] Draw a favicon in Pixelmator
- [x] Export it to PNG with Alpha Channel
- [x] Declare Favicon in HTML

**Comment by yorkxin** [comment]
✈️ 如何

**Comment by ascendbruce** [comment]
Good idea! 反正我已經在頁面裡用了 `glyphicon-plane`

**Comment by ascendbruce** [comment]
@chitsaou 可以麻煩你處理這張票嗎？

**Comment by yorkxin** [comment]
@ascendbruce 好啊，我來試試看

**Comment by chitsaou** [comment]
Ref: https://github.com/audreyr/favicon-cheat-sheet

- [ ] Draw a favicon in Pixelmator
- [ ] Export it to PNG with Alpha Channel
- [ ] Declare Favicon in HTML

**Comment by yorkxin** [comment]
Downloaded a PNG version of FontAwesome 'plane' from: https://github.com/encharm/Font-Awesome-SVG-PNG/blob/master/black/png/256/plane.png

**Comment by ascendbruce** [comment]
Deployed
