### ISSUE TITLE
網站失效

### ISSUE THREAD

**Issue by mythnc** [taiwanese-work-in/foreign-country#20]
wiki頁面此段落的網站已失效
https://github.com/taiwanese-work-in/foreign-country/wiki#%E8%96%AA%E6%B0%B4%E8%88%87%E7%94%9F%E6%B4%BB%E6%B0%B4%E5%B9%B3

Moving abroad, what salary to aim for?
http://rkh.im/move

**Comment by yorkxin** [comment]
感謝回報。去信詢問中。

**Comment by ascendbruce** [comment]
確認已關站，我們這邊也沒辦法做什麼，只能把我們這邊的頁面更新了

**Comment by mythnc** [comment]
感謝幫忙查詢！
