### ISSUE TITLE
遠傳月租30元方案

### ISSUE THREAD

**Issue by mythnc** [taiwanese-work-in/foreign-country#21]
wiki這個頁面提供了一些保留門號的方法
https://github.com/taiwanese-work-in/foreign-country/wiki/保留台灣的手機門號

查詢時發現遠傳有月租30元的低資費月租方案
https://www.fetnet.net/postpaid/rateplan/all-plan/others.html

因為是月租，理應可在國外收簡訊
https://www.backpackers.com.tw/forum/showthread.php?t=10002768#post10066323

供大家參考（我沒有編輯權限 XD）

**Comment by ascendbruce** [comment]
Hi @mythnc 

剛才更新進去了，謝謝提供資訊 😄 

(也順便把 foreign-country 的 wiki 編輯權限打開了)
